name: UnitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: ['2.1.300']
        os: [ubuntu-latest]
        include:
          - dotnet-version: '1.1.5'
            os: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: false
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: "Install and run tests 2.1.300"
        if: ${{  matrix.dotnet-version == '2.1.300' }}
        run: |
          dotnet test --framework netcoreapp2.0 tests_netcore/Plivo.NetCore.Test/Plivo.NetCore.Test.csproj;
        env:
          DOTNETCORE: 2
      - name: "Install and run tests 1.1.5"
        if: ${{  matrix.dotnet-version == '1.1.5' }}
        run: |
          sudo apt-get install 2.1.300-rc1-008673;
          dotnet test --framework netcoreapp1.1 tests_netcore/Plivo.NetCore.Test/Plivo.NetCore.Test.csproj;
        env:
          DOTNETCORE: 1
        
